---
title: "Vietnam education dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: paper
    orientation: rows
    vertical_layout: scroll
runtime:: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(echarts4r)
library(DT)
library(plotly)
library(here)
library(shiny)
library(scales)
library(glue)
## load file

geojson_map <- read_rds("cleanded-data/geojson_vnmap.rds")
school_stat <- read_rds("cleanded-data/education/n_school-student-teacher.rds") 

school_stat <- school_stat %>% 
  mutate(clean_name = if_else(clean_name == "tp_ho_chi_minh", "ho_chi_minh", clean_name)) %>% 
  mutate(stu_class = n_student/ n_class,
         teacher_class= n_teacher/ n_class,
         stu_teacher= n_student/n_teacher) %>% 
  pivot_longer(cols = -c(clean_name, dia_phuong, year, education_level)) %>% 
  mutate(value = round(value,1)) 
 

```


Detail on province {data-navmenu="Choose tab"}
=====================================================================================================
```{r include=FALSE}
## theme and color
theme_set(theme_classic(base_family = "Montserrat"))
theme_facet <- theme(strip.text = element_text(face = "bold", color = "chocolate3",
                                  hjust = .5, size = 11),
                     text= element_text(family = "Montserrat"),
        strip.background = element_rect(fill = "gray90", color = "transparent"),
        panel.grid.major.y = element_line(colour = "white", linetype = 3),
        plot.background = element_rect(fill = "#E7D5BD"),
        panel.background = element_rect(fill = "grey90"))

my_pal<- c("#62959c", "#c19277", "#e1bc91", "#e3d0b9","#9dad7f", "#726a95",
           "#d6b0b1", "#8b5e83")

graduate_rate <- read_rds("cleanded-data/education/highschool_graduated.rds")
```


Column {.sidebar data-width=250}
-----------------------------------------------------------------------
<br/>

```{r}
province <- setNames(unique(school_stat$clean_name), unique(school_stat$dia_phuong))

edu <- setNames(unique(school_stat$education_level),
                          c("Elementary school", "Middle school", "High school"))

selectInput("prov", "Choose province:",  choices = province, multiple = TRUE, selected = c("ha_tinh", "nghe_an"))
selectInput("edu", "Education level:", choices = edu)
```

Row {.tabset .tabset-fade data-height=800}
-----------------------------------------------------------------------

### General information

```{r}
raw_info <- tibble(name = c("n_class", "n_student", "n_teacher", "n_school"),
                   label = c(
    "Number of classes",
    "Number of students",
    "Number of teachers",
    "Number of schools"
  ))

#1 chart on raw data
renderPlotly({
  (school_stat %>% 
  filter(clean_name %in% input$prov) %>% 
  filter(education_level %in% input$edu) %>% 
  filter(name %in% raw_info$name) %>% 
  left_join(raw_info) %>% 
  mutate(dia_phuong = fct_reorder(dia_phuong, value, .fun = max)) %>% 
  ggplot(aes(year, value, group = dia_phuong, color = dia_phuong,
             text = glue("Year: {year}
                         {label}: {value}
                         Province: {dia_phuong}"))) +
  geom_point(size =.9)+
  geom_line(size= .3)+
  scale_y_continuous(labels = comma, n.breaks = 5)+
  scale_x_discrete(breaks = seq(2002, 2019, 3))+
  scale_color_manual(values = my_pal[1:length(input$prov)])+
  facet_wrap(~label, scale = "free")+
  labs(x= NULL,
       y= NULL,
       color = NULL)+
    theme_facet) %>% 
  ggplotly(tooltip = c("text")) %>% 
    config(displayModeBar = FALSE)
  })
```

### Highschoold graduated rate

```{r}
#2 chart 2: tile on graduate rate
renderEcharts4r({
  graduate_rate %>% 
  filter(clean_name %in% input$prov) %>% 
  e_charts(year) %>% 
  e_heatmap(dia_phuong, pct_graduated) %>% 
  e_visual_map(pct_graduated) %>% 
  e_title("Graduated rate (%)")
})

```

General education statistic {data-navmenu="Choose tab"}
=====================================================================================================

Column {.sidebar data-width=250}
-----------------------------------------------------------------------
<br/>

```{r}
education_lvl <- setNames(unique(school_stat$education_level),
                          c("Elementary school", "Middle school", "High school"))

category <- setNames(unique(school_stat$name),
                     c("Number of student",
                      "Number of teacher",
                      "Number of school",
                      "Number of class",
                      "Student-class-ratio",
                      "Teacher-class-ratio",
                      "Student-teacher-ratio"))
selectInput("education", "Education Stage", choices = education_lvl)
selectInput("category", "Information", choices = category)

```


Row {.tabset .tabset-fade data-height=800}
-----------------------------------------------------------------------

### Data on map

```{r}
renderEcharts4r({
  title = names(category[category == input$category])
  school_stat %>% 
  filter(name %in% input$category,
         education_level %in% input$education) %>% 
  group_by(year) %>% 
  e_charts(clean_name,timeline = TRUE) %>%
  e_map_register("vn", geojson_map) %>%
  e_map(value, map = "vn") %>%
  e_visual_map(value) %>%
  e_theme("infographic") %>% 
  e_title(text = glue("{ title } across all province"))
})

```

### Data on table

```{r}

renderDataTable({
  school_stat %>% 
  filter(name %in% input$category,
         education_level %in% input$education) %>% 
    select(dia_phuong, name, value) %>% 
    datatable(extensions = c("Buttons","Responsive"),
  options = list(
    dom = "Bfrtip",
    buttons = c("csv")))
})
```



